### ISSUE TITLE
Error {"error":"Client not initalized"}

### ISSUE THREAD

**Issue by Meerhoven** [baldarn/whatsapper-ha-integration#1]
Hi,
Thank you for this integration. I run into a problem, maybe some can help me.
I have installed the integration and it is running.
When I go to ip address 192.168.x.x:4000 the site is empty, when I go to 192.168.x.x:4000/chats I receive the message that the client is not initialized.

What is causing this? Should I change something in the setting?
Thanks JW

**Comment by baldarn** [comment]
hi, I think you must enable the addon scanning the qr code with WhatsApp app.

**Comment by Meerhoven** [comment]
Hi Baldarn. thank you for your response.
I have reinstalled everything, scanning qr in Whatsapp is working now. The integration is linked (mac os).
But I still get a blank page when I visit  192.168.x.x:4000.

**Comment by baldarn** [comment]
mmm could you paste the content of the configuration regarding Whatsapper?

**Comment by Meerhoven** [comment]
This is the code in configuration.yaml, I tried with or without the host port in de config.

notify:
  - platform: whatsapper
    name: Whatsapp berichten
    host_port: 192.168.2.141:4000 
    chat_id: xxxxxx@c.us

**Comment by baldarn** [comment]
if I understand correctly, you are running an instance in another machine.

if this is so, maybe you have to check firewall rules of the machine where Whatsapper is running.

I feel like this could be the issue.

**Comment by baldarn** [comment]
ok, have you added the integration with hacs?

if everything is in the same machine you can remove the `host_port` configuration.

the default should work with the home assistant running on the same host of Whatsapper

**Comment by baldarn** [comment]
the integration is not jet merged in HACS.

you have to add that as another repository

**Comment by Meerhoven** [comment]
that was the step I clearly forgot, thank you for pointing me in the right direction!

**Comment by baldarn** [comment]
great! is this solved?
