### ISSUE TITLE
Not sending notifications

### ISSUE THREAD

**Issue by MEOoms** [baldarn/whatsapper-ha-integration#3]
Hi, I installed the add-on and integration, edited the config to add the notify section.
The QR code accepted ok so I guess the install went correctly.
But when I try to send a notification, it is not received.
No evidence of anything being sent in the log file either.
Are there special requirements when sending the whatsapper notification from HA, e.g. in the message or data fields?
I just put the word test in the message field.

**Comment by baldarn** [comment]
mmm nothing special is required. could you give me the exact steps and the Whatsapper conf?

**Comment by MEOoms** [comment]
I installed the add-on, scanned QR code. In mylocalip:4000 I scanned the QR code, which was accepted.
Got the list with contacts there too.
Then edited configuration.yaml:
notify:
  - platform: whatsapper
    name: FamOomsWhatsapp
    host_port: 192.168.0.115:4000 
    chat_id: 3164873XXXX@c.us # WhatsApp chat id 

I then tried the notify FamOomsWhatsapp service, with test in the message field.
No error reported, but no message either

**Comment by baldarn** [comment]
if you have installed that with the addon manager, try removing the `host_port` part

**Comment by MEOoms** [comment]
Works!
Thanks a lot

**Comment by MEOoms** [comment]
Very nice add-on! Too bad there is not a lot attention for it. but I'm sure it will become popular because it is not dependent on access via a third party api.
