### ISSUE TITLE
Integration 'whatsapper' not found.

### ISSUE THREAD

**Issue by der-robert** [baldarn/whatsapper-ha-integration#4]
I installed the addon, initialize the app (under /chats i can see all my chats).
I add the example code to my configuration.yaml (i change name and chat_id).
If i check my configuration, i get the message: "Platform error 'notify' from integration 'whatsapper' - Integration 'whatsapper' not found."

**Comment by baldarn** [comment]
maybe you have to install the integration. this is still not merged in HACS, you can try this:

```
Installation

Whatsapper is still not part ot the Default HACS repositories list.

To add this, add this repository as custom repository in HACS, then install it searching whatsapper in the search form.
```

let me know if you need further assistance ;)

**Comment by der-robert** [comment]
Case Closed ... notice for me, read the readme :-)

**Comment by baldarn** [comment]
> Case Closed ... notice for me, read the readme :-)

no, I change that ;)

so that was my fault!

thanks for forcing me update that ;)
